### ISSUE TITLE
Fix 'index out of range' error

### ISSUE THREAD

**Issue by skatsuta** [skatsuta/gojit#1]
When I run `mandelbrot.bf`, `index out of range` error occurs.

```bash
$ time go run gobf/main.go ~/src/github.com/skatsuta/brainfuck-jit-go/test/mandelbrot.bf
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/nelhage/gojit/amd64.(*Assembler).byte(...)
        /Users/skatsuta/src/github.com/nelhage/gojit/amd64/assembler.go:55
github.com/nelhage/gojit/amd64.(*Assembler).Arithmetic(0xc42007e1b0, 0xc420060240, 0x4157d80, 0xc4200cb810, 0x4157dc0, 0xc4200cb814)
        /Users/skatsuta/src/github.com/nelhage/gojit/amd64/geninst.go:61 +0x5c8
github.com/nelhage/gojit/amd64.(*Assembler).Subb(0xc42007e1b0, 0x4157d80, 0xc4200cb810, 0x4157dc0, 0xc4200cb814)
        /Users/skatsuta/src/github.com/nelhage/gojit/amd64/geninst.go:147 +0x5f
github.com/nelhage/gojit/bf.Compile(0xc42008a000, 0x2dcf, 0x2fcf, 0x41572c0, 0xc42000e010, 0x4157300, 0xc42000e018, 0x400de6b, 0xc42001416b, 0xc420053f1d)
        /Users/skatsuta/src/github.com/nelhage/gojit/bf/bf.go:157 +0x54f
main.main()
        /Users/skatsuta/src/github.com/skatsuta/gojit/gobf/main.go:35 +0x30f
exit status 2
go run gobf/main.go   0.26s user 0.27s system 92% cpu 0.581 total
```

**Comment by skatsuta** [comment]
Fixed in #2.
